### ISSUE TITLE
Hardcoded log directory doesn't allow for password server to run in Windows

### ISSUE THREAD

**Issue by gschizas** [CboeSecurity/password_pwncheck#2]
https://github.com/CboeSecurity/password_pwncheck/blob/9052a16d3fd9e67319c0166837cde3bd2f03aefe/pwned_password_server/pwned-password-server.py#L41

There should be some decision according to the platform where to save logs.

**Comment by Beercow** [comment]
Couldn’t you just change the path to what you want? Seems rather trivial.

**Comment by CboeSecurity** [comment]
Good point, I'll add support on the command line or environment variable.

**Comment by CboeSecurity** [comment]
I've changed the log file to be "None" by default on Windows, and configurable on the command line.
